package highlighting.color;

public enum ColorType {
    STRING_LITERAL_COLOUR,
    CHAR_LITERAL_COLOUR,
    KEYWORD_COLOUR,
    ANNOTATION_COLOUR,
    LINE_COMMENT_COLOUR,
    BLOCK_COMMENT_COLOUR,
    JAVADOC_COMMENT_COLOUR,
    IDENTIFIER_COLOUR,
    NUMBER_COLOUR,
    OPERATOR_COLOUR,
    CLASS_NAME_COLOUR,
    METHOD_NAME_COLOUR,
    METHOD_CALL_COLOUR,
    CONSTRUCTOR_CALL_COLOUR,
    CONSTANT_COLOUR,
    PARAMETER_COLOUR,
}
